import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shahid Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >

        {/* GLOBAL BACKGROUND */}
        <div className="fixed inset-0 -z-10">

          {/* GRID */}
          <div className="absolute inset-0 opacity-20 pointer-events-none">
            <svg className="w-full h-full">
              <defs>
                <pattern id="grid-global" width="60" height="60" patternUnits="userSpaceOnUse">
                  <path d="M 60 0 L 0 0 0 60" fill="none" stroke="cyan" strokeWidth="0.4" />
                </pattern>
              </defs>
              <rect width="100%" height="100%" fill="url(#grid-global)" />
            </svg>
          </div>

          {/* GLOW */}
          <div className="absolute w-[500px] h-[500px] bg-cyan-500/20 blur-[200px] top-0 left-0 pointer-events-none"></div>
          <div className="absolute w-[400px] h-[400px] bg-purple-500/20 blur-[200px] bottom-0 right-0 pointer-events-none"></div>

        </div>

        {/* PAGE CONTENT */}
        {children}

      </body>
    </html>
  );
}